services:
  app:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:54322/postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
